name: CI

on:
  push:
    branches-ignore: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm test --silent | cat
      - name: Smoke render payload and HTML
        run: |
          node -e "import('./utils/formatter.js').then(m => { const r = m.formatMessage({ source:'SMOKE', title:'Test Alert', link:'https://example.com', description:'desc', publishedDate:new Date().toISOString(), feedMetadata:{} }); console.log(JSON.stringify(r.payload)); })" > teams-payload.json
          node -e "import('./outputs/githubPages-enhanced.js').then(m => new m.GitHubPagesOutput().generateFeed([{title:'Test',url:'https://example.com',description:'desc',publishedDate:new Date().toISOString(),feedName:'SMOKE'}]).then(()=>{}))"
          test -f docs/index.html && cp docs/index.html html-snippet.html || echo "<html>No HTML</html>" > html-snippet.html
      - name: Upload smoke artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            teams-payload.json
            html-snippet.html

