name: RSS to Teams Bot

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run threat feed bot
      env:
        TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        NODE_ENV: production
      run: npm start
    
    - name: Commit and push state changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add state.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update state.json - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
