name: DEPRECATED - Use Staging/Production

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use Staging or Production which call run-feed-reusable.yml"
