name: Run Threat Feed (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      enablePages:
        required: false
        type: boolean
        default: false
    secrets:
      TEAMS_WEBHOOK_URL:
        required: true
      PERSONAL_ACCESS_TOKEN:
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ inputs.environment }}
    env:
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate configuration
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: node scripts/validate-config.js

      - name: Run feed
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          ENABLE_GITHUB_PAGES: ${{ inputs.enablePages && 'true' || 'false' }}
          PER_RUN_POST_CAP: '30'
          POST_DELAY_MS: '1000'
          TEAMS_MAX_RETRIES: '5'
        run: npm start | cat

      - name: Generate state report
        if: always()
        run: node scripts/state-doctor.js | cat

      - name: Collect metrics artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-metrics
          path: |
            data/metrics.json
            data/state-report.json
          if-no-files-found: ignore

      - name: Commit state and docs (if changed)
        if: success() && inputs.enablePages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/state.json docs/index.html docs/feed.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update state and docs"
            git push
          fi

